build_platform: {osx_arm64: osx_64, win_arm64: win_arm64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
    - pull_request
provider:
  win_arm64: github_actions
conda_build:
  pkg_format: '2'
test: native_and_emulated